### PR TITLE
Homepage, ProductPage, Routes added

### PR DESCRIPTION
**Pull request by vaibhav18matere**
- Home page added
-  Product page added
- Single product card added
- login, signup, password page added
- wishlist, cart page added
- Routes added
- products (cars) database file added
- dynamic routing added

### CODE REVIEW

**Review by SanjayJatti — APPROVED** [review]
- Try to have small size PR further 
- Otherwise good folder structure
- Code is clean

**Review by aayushjain-code — APPROVED** [review]
Everything Looks good you can merge it!

**Comment by vaibhav18matere** [comment]
> * Try to have small size PR further
> * Otherwise good folder structure
> * Code is clean

Sure, Will keep in mind. Thanks

**Comment by vaibhav18matere** [comment]
> Everything Looks good you can merge it!

Sure, Thanks

**Pull request merged**
